spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  application:
    name: ${SPRING_APPLICATION_NAME?:account}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE?:prod}
  config:
    import: ${SPRING_CONFIG_IMPORT?:optional:configserver:http://localhost:8071}

eureka:
  client:
    enabled : ${EUREKA_ENABLED:false}
    healthcheck:
      enabled : true
    statusPageUrlPath: ${server.servletPath}/actuator/info
    healthCheckUrlPath: ${server.servletPath}/actuator/health
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8070/eureka/}


server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
