version: "3.8"
services:
  config:
    image: davidchow/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - davidchow-network
    healthcheck:
      test: ["CMD-SHELL","curl http://localhost:8071/actuator"]
      interval: 10s
      timeout: 5s
      retries: 5
  accounts:
    image: davidchow/account:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - davidchow-network
    depends_on:
      config:
        condition: service_healthy
  loans:
    image: davidchow/loan:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - davidchow-network
    depends_on:
      config: 
        condition: service_healthy
  cards:
    image: davidchow/card:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - davidchow-network
    depends_on: 
      config: 
        condition: service_healthy
networks:
  davidchow-network:
    driver: bridge
