spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  application:
    name: ${SPRING_APPLICATION_NAME?:card}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE?:prod}
  config:
    import: ${SPRING_CONFIG_IMPORT?:optional:configserver:http://localhost:8071}

server:
  port: 9000

info:
  application:
    name: Card Microservice
    description: David Chow Card Application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
management:
  info:
    env:
      enabled : true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
endpoints:
  shutdown:
    enabled: true
eureka:
  client:
    registerWithEureka : true
    fetchRegistry: true
    enabled : ${EUREKA_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8070/eureka/}
  instance:
    preferIAddress : true


