version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - davidchow-network
  zipkin:
    image: openzipkin/zipkin:latest
    mem_limit: 200m
    ports:
      - "9411:9411"
    networks:
      - davidchow-network
  config:
    image: davidchow/configserver:latest
    mem_limit: 200m
    ports:
      - "8071:8071"
    networks:
      - davidchow-network
    healthcheck:
      test: ["CMD-SHELL","curl http://localhost:8071/actuator"]
      interval: 10s
      timeout: 5s
      retries: 5
  discovery:
    image: davidchow/discovery:latest
    mem_limit: 500m
    ports:
      - "8070:8070"
    networks:
      - davidchow-network
    depends_on:
      config:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","curl http://localhost:8070/actuator"]
      interval: 10s
      timeout: 5s
      retries: 5
  gatewayserver:
    image: davidchow/gatewayserver:latest
    mem_limit: 500m
    ports:
      - "8072:8072"
    networks:
      - davidchow-network
    depends_on:
      discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","curl http://localhost:8072/actuator"]
      interval: 20s
      timeout: 10s
      retries: 5
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_SERVER: http://discovery:8070/eureka/
      EUREKA_ENABLED: "true"
      ZIPKIN_SERVER: http://zipkin:9411
  accounts:
    image: davidchow/account:latest
    mem_limit: 600m
    ports:
      - "8080:8080"
    networks:
      - davidchow-network
    depends_on:
      gatewayserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_PROILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_SERVER: http://discovery:8070/eureka/
      EUREKA_ENABLED: "true"
      ZIPKIN_SERVER: http://zipkin:9411
  loans:
    image: davidchow/loan:latest
    mem_limit: 600m
    ports:
      - "8090:8090"
    networks:
      - davidchow-network
    depends_on:
      gatewayserver: 
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_PROILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_SERVER: http://discovery:8070/eureka/
      EUREKA_ENABLED: "true"
      ZIPKIN_SERVER: http://zipkin:9411
  cards:
    image: davidchow/card:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - davidchow-network
    depends_on: 
      gatewayserver: 
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_PROILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_SERVER: http://discovery:8070/eureka/
      EUREKA_ENABLED: "true"
      ZIPKIN_SERVER: http://zipkin:9411
networks:
  davidchow-network:
    driver: bridge
