version: "3.8"
services:
  config:
    image: davidchow/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - davidchow-network
    healthcheck:
      test: ["CMD-SHELL","curl http://localhost:8071/actuator"]
      interval: 10s
      timeout: 5s
      retries: 5
  discovery:
    image: davidchow/discovery:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - davidchow-network
    depends_on:
      config:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","curl http://localhost:8070/actuator"]
      interval: 10s
      timeout: 5s
      retries: 5
  accounts:
    image: davidchow/account:latest
    mem_limit: 700m
    ports:
      - "8080-8085:8080"
    networks:
      - davidchow-network
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      SPRING_APPLIATION_NAME: account
      SPRING_PROILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_SERVER: http://discovery:8070/eureka/
      EUREKA_ENABLED: "true"
  loans:
    image: davidchow/loan:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - davidchow-network
    depends_on:
      discovery: 
        condition: service_healthy
    environment:
      SPRING_APPLIATION_NAME: loan
      SPRING_PROILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_SERVER: http://discovery:8070/eureka/
      EUREKA_ENABLED: "true"
  cards:
    image: davidchow/card:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - davidchow-network
    depends_on: 
      discovery: 
        condition: service_healthy
    environment:
      SPRING_APPLIATION_NAME: card
      SPRING_PROILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://config:8071/
      EUREKA_SERVER: http://discovery:8070/eureka/
      EUREKA_ENABLED: "true"
networks:
  davidchow-network:
    driver: bridge
